version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ../Sites/entree:/var/www/html
    privileged: true
    #tty: true
    #command: "/bin/sh"
  db:
    image: orchardup/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wordpress
